// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveTabController from "./active_tab_controller"
application.register("active-tab", ActiveTabController)

import CategorySearchController from "./category_search_controller"
application.register("category-search", CategorySearchController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GoogleMapsController from "./google_maps_controller"
application.register("google-maps", GoogleMapsController)

import GoogleSearchController from "./google_search_controller"
application.register("google-search", GoogleSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItinCollapseController from "./itin_collapse_controller"
application.register("itin-collapse", ItinCollapseController)

import SearchBarController from "./search_bar_controller"
application.register("search-bar", SearchBarController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)
